on:
  workflow_dispatch:
  schedule:
    # runs every day at 0,6,12,18 UTC in Jan, Feb, Sep-Dec
    - cron: '0 */6 * 9-12,1 *'
    - cron:  '0 */6 1-15 2 *'
    
name: update_adv_stats

jobs:
  pfr_advstats:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.NFLVERSE_GH_TOKEN }}
      SCRAPEOPS_API_KEY: ${{ secrets.NFLVERSE_SCRAPEOPS_API_KEY }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages:  |
            local::.
            nflverse/nflverse-data
            nflverse/undercover
            ropensci/piggyback

      - name: Run update script
        run: Rscript -e 'source("auto/update_adv_stats.R")'

      - name: Run update script
        run: Rscript -e 'source("auto/update_adv_season_stats.R")'
